module SkelLatte where

-- Haskell module generated by the BNF converter

import AbsLatte
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident string -> failure x
transProgram :: Program -> Result
transProgram x = case x of
  Prog topdefs -> failure x
transTopDef :: TopDef -> Result
transTopDef x = case x of
  FnDef funcdef -> failure x
  ClassDef ident cdef -> failure x
  ClassDefExt ident1 ident2 cdef -> failure x
transArg :: Arg -> Result
transArg x = case x of
  Arg type_ ident -> failure x
transFuncDef :: FuncDef -> Result
transFuncDef x = case x of
  FunDef type_ ident args block -> failure x
transCDef :: CDef -> Result
transCDef x = case x of
  ClassBlock classelems -> failure x
transClassElem :: ClassElem -> Result
transClassElem x = case x of
  ClassMeth funcdef -> failure x
  ClassAtr type_ ident -> failure x
transBlock :: Block -> Result
transBlock x = case x of
  Block stmts -> failure x
transStmt :: Stmt -> Result
transStmt x = case x of
  Empty -> failure x
  BStmt block -> failure x
  Decl type_ items -> failure x
  Ass lvalue expr -> failure x
  Incr lvalue -> failure x
  Decr lvalue -> failure x
  Ret expr -> failure x
  VRet -> failure x
  Cond expr stmt -> failure x
  CondElse expr stmt1 stmt2 -> failure x
  While expr stmt -> failure x
  For type_ ident1 ident2 stmt -> failure x
  SExp expr -> failure x
transItem :: Item -> Result
transItem x = case x of
  NoInit ident -> failure x
  Init ident expr -> failure x
transType :: Type -> Result
transType x = case x of
  Arr type_ -> failure x
  Int -> failure x
  Str -> failure x
  Fun type_ types -> failure x
  Bool -> failure x
  Void -> failure x
  Obj ident -> failure x
transExpr :: Expr -> Result
transExpr x = case x of
  ECastNull type_ -> failure x
  EAttrAccess attraccess -> failure x
  EMthCall methodcall -> failure x
  EArrAccess arrelemaccess -> failure x
  EVar ident -> failure x
  ENewArr type_ expr -> failure x
  ENew ident -> failure x
  ELitInt integer -> failure x
  ELitTrue -> failure x
  ELitFalse -> failure x
  EApp functioncall -> failure x
  EString string -> failure x
  Neg expr -> failure x
  Not expr -> failure x
  EMul expr1 mulop expr2 -> failure x
  EAdd expr1 addop expr2 -> failure x
  ERel expr1 relop expr2 -> failure x
  EAnd expr1 expr2 -> failure x
  EOr expr1 expr2 -> failure x
transFunctionCall :: FunctionCall -> Result
transFunctionCall x = case x of
  FunctionCall ident exprs -> failure x
transArrElemAccess :: ArrElemAccess -> Result
transArrElemAccess x = case x of
  ArrayElem lvalue expr -> failure x
transAttrAccess :: AttrAccess -> Result
transAttrAccess x = case x of
  AttrAcc lvalue ident -> failure x
transMethodCall :: MethodCall -> Result
transMethodCall x = case x of
  MCall lvalue functioncall -> failure x
transLValue :: LValue -> Result
transLValue x = case x of
  LVFunCall functioncall -> failure x
  LVMethodCall methodcall -> failure x
  LVJustIdent ident -> failure x
  LVArrayAcc arrelemaccess -> failure x
  LVAttrAcc attraccess -> failure x
transAddOp :: AddOp -> Result
transAddOp x = case x of
  Plus -> failure x
  Minus -> failure x
transMulOp :: MulOp -> Result
transMulOp x = case x of
  Times -> failure x
  Div -> failure x
  Mod -> failure x
transRelOp :: RelOp -> Result
transRelOp x = case x of
  LTH -> failure x
  LE -> failure x
  GTH -> failure x
  GE -> failure x
  EQU -> failure x
  NE -> failure x

